import { Inter } from "next/font/google";
import Navber from "../Components/Navber";
import Footer from "../Components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create About page",
  description: "Generated by create About page",
};

export default function AboutLayout({ children }) {
  return (
    <div>
        <Navber/>
        {children}
        <Footer/>
    </div>
  );
}
