import { Inter } from "next/font/google";
import Navber from "../Components/Navber";
import Footer from "../Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Franchise page app",
  description: "Generated by create Franchise page app",
};

export default function FranchiseLayout({ children }) {
  return (
    <div>
        <Navber/>
        {children}
        <Footer/>
    </div>
  );
}
